### ISSUE TITLE
RefCount error

### ISSUE THREAD

**Issue by zhouhang95** [damyanp/directx-graphics-samples-rs#1]
https://github.com/damyanp/directx-graphics-samples-rs/blob/36d7084ada4b6a6bd8d2f303161decc16567f8f7/d3dx12/src/lib.rs#L21

In this line, RefCount += 1.
But this is in std::mem::ManuallyDrop, The resource never release.

Or can I directly  make RefCount -=1 by windows-rs api?

**Comment by damyanp** [comment]
Thank you for reporting this!
